//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstitutionalSupportFundEntities : DbContext
    {
        public InstitutionalSupportFundEntities()
            : base("name=InstitutionalSupportFundEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnualSummary> AnnualSummary { get; set; }
        public virtual DbSet<Layers> Layers { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductsToReasons> ProductsToReasons { get; set; }
        public virtual DbSet<ProductsToSupports> ProductsToSupports { get; set; }
        public virtual DbSet<Protocols> Protocols { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<ReasonsForSupports> ReasonsForSupports { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Responsibles> Responsibles { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Supporteds> Supporteds { get; set; }
        public virtual DbSet<Supports> Supports { get; set; }
        public virtual DbSet<SupportWay> SupportWay { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TransactionsOnCoffer> TransactionsOnCoffer { get; set; }
        public virtual DbSet<TypesOfExpensesAndIncome> TypesOfExpensesAndIncome { get; set; }
    }
}
