//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsToReasons
    {
        public int ProdToReasonID { get; set; }
        public Nullable<int> ProdID { get; set; }
        public Nullable<int> ReasonID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual ReasonsForSupports ReasonsForSupports { get; set; }
    }
}
