//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsToReasons = new HashSet<ProductsToReasons>();
        }
    
        public int ProdID { get; set; }
        public string ProdName { get; set; }
        public Nullable<int> providerID { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<int> SupportWayID { get; set; }
    
        public virtual Providers Providers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsToReasons> ProductsToReasons { get; set; }
    }
}
