//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocols
    {
        public int ProtocolID { get; set; }
        public Nullable<int> SupportedToProtocol { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> ReasonForProtocol { get; set; }
        public Nullable<int> SupportID { get; set; }
    
        public virtual ReasonsForSupports ReasonsForSupports { get; set; }
        public virtual Supports Supports { get; set; }
    }
}
