//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ReportID { get; set; }
        public Nullable<int> SupportedID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Details { get; set; }
        public Nullable<int> GabayID { get; set; }
    
        public virtual Responsibles Responsibles { get; set; }
        public virtual Supporteds Supporteds { get; set; }
    }
}
