//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsibles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Responsibles()
        {
            this.Reports = new HashSet<Reports>();
            this.Supports = new HashSet<Supports>();
        }
    
        public int ResponsibleID { get; set; }
        public string ResponsibleName { get; set; }
        public Nullable<bool> AllowingAccess { get; set; }
        public string LoginPassword { get; set; }
        public string ResponsibleTelephone { get; set; }
        public string ResponsibleEmail { get; set; }
        public Nullable<bool> Participant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supports> Supports { get; set; }
    }
}
