//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supporteds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supporteds()
        {
            this.Reports = new HashSet<Reports>();
            this.Supports = new HashSet<Supports>();
        }
    
        public int SupportedID { get; set; }
        public string SupFirstName { get; set; }
        public string SupLastName { get; set; }
        public Nullable<int> LayerID { get; set; }
        public string SupTelephone { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string SupportedIdentity { get; set; }
        public byte[] gambar { get; set; }
    
        public virtual Layers Layers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supports> Supports { get; set; }
    }
}
