//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportWay
    {
        public int SupportWayID { get; set; }
        public string PaymentWay { get; set; }
        public string NoteToProtocol { get; set; }
        public Nullable<bool> BlackOrWhite { get; set; }
    }
}
