//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supports()
        {
            this.Protocols = new HashSet<Protocols>();
        }
    
        public int SupportID { get; set; }
        public Nullable<int> SupportedID { get; set; }
        public Nullable<System.DateTime> SuppDate { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<decimal> SumOfSupport { get; set; }
        public string Details { get; set; }
        public Nullable<int> ResponsibleID { get; set; }
        public string Referrer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Protocols> Protocols { get; set; }
        public virtual ReasonsForSupports ReasonsForSupports { get; set; }
        public virtual Responsibles Responsibles { get; set; }
        public virtual Supporteds Supporteds { get; set; }
    }
}
